:sparkles: Add pre-commit workflow for code quality checks
- Add pre-commit workflow for code quality checks
- Add pre-commit configuration file
- Add cache directory for cppcheck
- Add pre-commit hooks for code formatting, linting, and static analysis

diff --git a/cmd-or-msg b/cmd-or-msg
--- a/cmd-or-msg
+++ b/cmd-or-msg
@@ -6,6 +6,6 @@ shift
 
 echo "$*"
 if ! "${@}"; then
-    echo "If you can't fix the issue, re-run $srcdir/configure with --$opt."
-    exit 1
+  echo "If you can't fix the issue, re-run $srcdir/configure with --$opt."
+  exit 1
 fi
diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5,23 +5,23 @@
 
 dir=`dirname $0`
 if test x"$dir" = x; then
-    dir=.
+  dir=.
 fi
 
 if test "$dir" = '.'; then
-    branch=`packaging/prep-auto-dir` || exit 1
-    if test x"$branch" != x; then
-	cd build || exit 1
-	dir=..
-    fi
+  branch=`packaging/prep-auto-dir` || exit 1
+  if test x"$branch" != x; then
+    cd build || exit 1
+    dir=..
+  fi
 fi
 
 if test ! -f configure.sh; then
-    if ! "$dir/prepare-source" build; then
-	echo 'Failed to build configure.sh and/or config.h.in -- giving up.' >&2
-	rm -f configure.sh
-	exit 1
-    fi
+  if ! "$dir/prepare-source" build; then
+    echo 'Failed to build configure.sh and/or config.h.in -- giving up.' >&2
+    rm -f configure.sh
+    exit 1
+  fi
 fi
 
 exec ./configure.sh --srcdir="$dir" "${@}"
diff --git a/maybe-make-man b/maybe-make-man
--- a/maybe-make-man
+++ b/maybe-make-man
@@ -1,8 +1,8 @@
 #!/bin/sh
 
 if [ $# != 1 ]; then
-    echo "Usage: $0 NAME.NUM.md" 1>&2
-    exit 1
+  echo "Usage: $0 NAME.NUM.md" 1>&2
+  exit 1
 fi
 
 inname="$1"
@@ -11,32 +11,32 @@ flagfile="$srcdir/.md2man-works"
 force_flagfile="$srcdir/.md2man-force"
 
 if [ ! -f "$flagfile" ]; then
-    # We test our smallest manpage just to see if the python setup works.
-    if "$srcdir/md-convert" --test "$srcdir/rsync-ssl.1.md" >/dev/null 2>&1; then
-	touch $flagfile
+  # We test our smallest manpage just to see if the python setup works.
+  if "$srcdir/md-convert" --test "$srcdir/rsync-ssl.1.md" >/dev/null 2>&1; then
+    touch $flagfile
+  else
+    outname=`basename "$inname" .md`
+    if [ -f "$outname" ]; then
+      exit 0
+    elif [ -f "$srcdir/$outname" ]; then
+      echo "Copying $srcdir/$outname"
+      cp -p "$srcdir/$outname" .
+      exit 0
     else
-	outname=`basename "$inname" .md`
-	if [ -f "$outname" ]; then
-	    exit 0
-	elif [ -f "$srcdir/$outname" ]; then
-	    echo "Copying $srcdir/$outname"
-	    cp -p "$srcdir/$outname" .
-	    exit 0
-	else
-	    echo "ERROR: $outname cannot be created."
-	    if [ -f "$HOME/build_farm/build_test.fns" ]; then
-		exit 0 # No exit errorno to avoid a build failure in the samba build farm
-	    else
-		exit 1
-	    fi
-	fi
+      echo "ERROR: $outname cannot be created."
+      if [ -f "$HOME/build_farm/build_test.fns" ]; then
+        exit 0 # No exit errorno to avoid a build failure in the samba build farm
+      else
+        exit 1
+      fi
     fi
+  fi
 fi
 
 if [ -f "$force_flagfile" ]; then
-    opt='--force-link-text'
+  opt='--force-link-text'
 else
-    opt=''
+  opt=''
 fi
 
 "$srcdir/md-convert" $opt "$srcdir/$inname"
