Only allow the build farm to rsync the latest generated configure files when building them fails.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -16,8 +16,12 @@ if [ ! -f "$realconfigure" ]; then
     make -f prepare-source.mak proto.h
     if make -f prepare-source.mak conf; then
 	:
-    else
+    elif [ -f "$HOME/build_farm/build_test.fns" ]; then
+	# Allow the build farm to grab latest files via rsync.
 	rsync -avz rsync://rsync.samba.org/rsyncftp/generated-files/'c*' .
+    else
+	echo 'Failed to build configure.sh and/or config.h.in -- giving up.' >&2
+	exit 1
     fi
     if test x"$curdir" != x; then
 	cd "$curdir"
