:sparkles: Add pre-commit workflow for code quality checks
- Add pre-commit workflow for code quality checks
- Add pre-commit configuration file
- Add cache directory for cppcheck
- Add pre-commit hooks for code formatting, linting, and static analysis

diff --git a/install-sh b/install-sh
--- a/install-sh
+++ b/install-sh
@@ -43,103 +43,103 @@ dst=""
 dir_arg=""
 
 while [ x"$1" != x ]; do
-    case $1 in
-	-c) instcmd="$cpprog"
-	    shift
-	    continue;;
+  case $1 in
+    -c) instcmd="$cpprog"
+      shift
+      continue ;;
 
-	-d) dir_arg=true
-	    shift
-	    continue;;
+    -d) dir_arg=true
+      shift
+      continue ;;
 
-	-m) chmodcmd="$chmodprog $2"
-	    shift
-	    shift
-	    continue;;
+    -m) chmodcmd="$chmodprog $2"
+      shift
+      shift
+      continue ;;
 
-	-o) chowncmd="$chownprog $2"
-	    shift
-	    shift
-	    continue;;
+    -o) chowncmd="$chownprog $2"
+      shift
+      shift
+      continue ;;
 
-	-g) chgrpcmd="$chgrpprog $2"
-	    shift
-	    shift
-	    continue;;
+    -g) chgrpcmd="$chgrpprog $2"
+      shift
+      shift
+      continue ;;
 
-	-s) stripcmd="$stripprog"
-	    shift
-	    continue;;
+    -s) stripcmd="$stripprog"
+      shift
+      continue ;;
 
-	-t=*) transformarg=`echo $1 | sed 's/-t=//'`
-	    shift
-	    continue;;
+    -t=*) transformarg=`echo $1 | sed 's/-t=//'`
+      shift
+      continue ;;
 
-	-b=*) transformbasename=`echo $1 | sed 's/-b=//'`
-	    shift
-	    continue;;
+    -b=*) transformbasename=`echo $1 | sed 's/-b=//'`
+      shift
+      continue ;;
 
-	*)  if [ x"$src" = x ]
-	    then
-		src=$1
-	    else
-		# this colon is to work around a 386BSD /bin/sh bug
-		:
-		dst=$1
-	    fi
-	    shift
-	    continue;;
-    esac
+    *)  if [ x"$src" = x ]
+      then
+        src=$1
+      else
+        # this colon is to work around a 386BSD /bin/sh bug
+        :
+        dst=$1
+      fi
+      shift
+      continue ;;
+  esac
 done
 
 if [ x"$src" = x ]
 then
-	echo "install:	no input file specified"
-	exit 1
+  echo "install:	no input file specified"
+  exit 1
 else
-	true
+  true
 fi
 
 if [ x"$dir_arg" != x ]; then
-	dst=$src
-	src=""
+  dst=$src
+  src=""
 
-	if [ -d $dst ]; then
-		instcmd=:
-	else
-		instcmd=mkdir
-	fi
+  if [ -d $dst ]; then
+    instcmd=:
+  else
+    instcmd=mkdir
+  fi
 else
 
-# Waiting for this to be detected by the "$instcmd $src $dsttmp" command
-# might cause directories to be created, which would be especially bad
-# if $src (and thus $dsttmp) contains '*'.
+  # Waiting for this to be detected by the "$instcmd $src $dsttmp" command
+  # might cause directories to be created, which would be especially bad
+  # if $src (and thus $dsttmp) contains '*'.
 
-	if [ -f $src ] || [ -d $src ]
-	then
-		true
-	else
-		echo "install:  $src does not exist"
-		exit 1
-	fi
+  if [ -f $src ] || [ -d $src ]
+  then
+    true
+  else
+    echo "install:  $src does not exist"
+    exit 1
+  fi
 
-	if [ x"$dst" = x ]
-	then
-		echo "install:	no destination specified"
-		exit 1
-	else
-		true
-	fi
+  if [ x"$dst" = x ]
+  then
+    echo "install:	no destination specified"
+    exit 1
+  else
+    true
+  fi
 
-# If destination is a directory, append the input filename; if your system
-# does not like double slashes in filenames, you may need to add some logic
+  # If destination is a directory, append the input filename; if your system
+  # does not like double slashes in filenames, you may need to add some logic
 
-	if [ -d $dst ]
-	then
-		dst="$dst"/`basename $src`
-	else
-		true
-	fi
+  if [ -d $dst ]
+  then
+    dst="$dst"/`basename $src`
+  else
+    true
+  fi
 fi
 
 ## this sed command emulates the dirname command
@@ -150,87 +150,87 @@ dstdir=`echo $dst | sed -e 's,[^/]*$,,;s,/$,,;s,^$,.,'`
 
 # Skip lots of stat calls in the usual case.
 if [ ! -d "$dstdir" ]; then
-defaultIFS='
+  defaultIFS='
 '
-IFS="${IFS-${defaultIFS}}"
+  IFS="${IFS-${defaultIFS}}"
 
-oIFS="${IFS}"
-# Some sh's can't handle IFS=/ for some reason.
-IFS='%'
-set - `echo ${dstdir} | sed -e 's@/@%@g' -e 's@^%@/@'`
-IFS="${oIFS}"
+  oIFS="${IFS}"
+  # Some sh's can't handle IFS=/ for some reason.
+  IFS='%'
+  set - `echo ${dstdir} | sed -e 's@/@%@g' -e 's@^%@/@'`
+  IFS="${oIFS}"
 
-pathcomp=''
+  pathcomp=''
 
-while [ $# -ne 0 ] ; do
-	pathcomp="${pathcomp}${1}"
-	shift
+  while [ $# -ne 0 ] ; do
+    pathcomp="${pathcomp}${1}"
+    shift
 
-	if [ ! -d "${pathcomp}" ] ;
-        then
-		$mkdirprog "${pathcomp}"
-	else
-		true
-	fi
+    if [ ! -d "${pathcomp}" ] ;
+    then
+      $mkdirprog "${pathcomp}"
+    else
+      true
+    fi
 
-	pathcomp="${pathcomp}/"
-done
+    pathcomp="${pathcomp}/"
+  done
 fi
 
 if [ x"$dir_arg" != x ]
 then
-	$doit $instcmd $dst &&
+  $doit $instcmd $dst &&
 
-	if [ x"$chowncmd" != x ]; then $doit $chowncmd $dst; else true ; fi &&
-	if [ x"$chgrpcmd" != x ]; then $doit $chgrpcmd $dst; else true ; fi &&
-	if [ x"$stripcmd" != x ]; then $doit $stripcmd $dst; else true ; fi &&
-	if [ x"$chmodcmd" != x ]; then $doit $chmodcmd $dst; else true ; fi
+  if [ x"$chowncmd" != x ]; then $doit $chowncmd $dst; else true ; fi &&
+  if [ x"$chgrpcmd" != x ]; then $doit $chgrpcmd $dst; else true ; fi &&
+  if [ x"$stripcmd" != x ]; then $doit $stripcmd $dst; else true ; fi &&
+  if [ x"$chmodcmd" != x ]; then $doit $chmodcmd $dst; else true ; fi
 else
 
-# If we're going to rename the final executable, determine the name now.
+  # If we're going to rename the final executable, determine the name now.
 
-	if [ x"$transformarg" = x ]
-	then
-		dstfile=`basename $dst`
-	else
-		dstfile=`basename $dst $transformbasename |
-			sed $transformarg`$transformbasename
-	fi
+  if [ x"$transformarg" = x ]
+  then
+    dstfile=`basename $dst`
+  else
+    dstfile=`basename $dst $transformbasename |
+    sed $transformarg`$transformbasename
+  fi
 
-# don't allow the sed command to completely eliminate the filename
+  # don't allow the sed command to completely eliminate the filename
 
-	if [ x"$dstfile" = x ]
-	then
-		dstfile=`basename $dst`
-	else
-		true
-	fi
+  if [ x"$dstfile" = x ]
+  then
+    dstfile=`basename $dst`
+  else
+    true
+  fi
 
-# Make a temp file name in the proper directory.
+  # Make a temp file name in the proper directory.
 
-	dsttmp=$dstdir/_inst.$$_
+  dsttmp=$dstdir/_inst.$$_
 
-# Move or copy the file name to the temp name
+  # Move or copy the file name to the temp name
 
-	$doit $instcmd $src $dsttmp &&
+  $doit $instcmd $src $dsttmp &&
 
-	trap "rm -f ${dsttmp}" 0 &&
+  trap "rm -f ${dsttmp}" 0 &&
 
-# and set any options; do chmod last to preserve setuid bits
+  # and set any options; do chmod last to preserve setuid bits
 
-# If any of these fail, we abort the whole thing.  If we want to
-# ignore errors from any of these, just make sure not to ignore
-# errors from the above "$doit $instcmd $src $dsttmp" command.
+  # If any of these fail, we abort the whole thing.  If we want to
+  # ignore errors from any of these, just make sure not to ignore
+  # errors from the above "$doit $instcmd $src $dsttmp" command.
 
-	if [ x"$chowncmd" != x ]; then $doit $chowncmd $dsttmp; else true;fi &&
-	if [ x"$chgrpcmd" != x ]; then $doit $chgrpcmd $dsttmp; else true;fi &&
-	if [ x"$stripcmd" != x ]; then $doit $stripcmd $dsttmp; else true;fi &&
-	if [ x"$chmodcmd" != x ]; then $doit $chmodcmd $dsttmp; else true;fi &&
+  if [ x"$chowncmd" != x ]; then $doit $chowncmd $dsttmp; else true;fi &&
+  if [ x"$chgrpcmd" != x ]; then $doit $chgrpcmd $dsttmp; else true;fi &&
+  if [ x"$stripcmd" != x ]; then $doit $stripcmd $dsttmp; else true;fi &&
+  if [ x"$chmodcmd" != x ]; then $doit $chmodcmd $dsttmp; else true;fi &&
 
-# Now rename the file to the real destination.
+  # Now rename the file to the real destination.
 
-	$doit $rmcmd -f $dstdir/$dstfile &&
-	$doit $mvcmd $dsttmp $dstdir/$dstfile
+  $doit $rmcmd -f $dstdir/$dstfile &&
+  $doit $mvcmd $dsttmp $dstdir/$dstfile
 
 fi &&
 
diff --git a/packaging/prep-auto-dir b/packaging/prep-auto-dir
--- a/packaging/prep-auto-dir
+++ b/packaging/prep-auto-dir
@@ -14,30 +14,30 @@
 
 auto_top='auto-build-save'
 if test -d $auto_top && test -d .git; then
-    desired_branch=`git rev-parse --abbrev-ref HEAD | tr / %`
-    if test "$desired_branch" = HEAD; then
-	echo "ERROR: switch to the right build dir manually when in detached HEAD mode." 1>&2
-	exit 1
+  desired_branch=`git rev-parse --abbrev-ref HEAD | tr / %`
+  if test "$desired_branch" = HEAD; then
+    echo "ERROR: switch to the right build dir manually when in detached HEAD mode." 1>&2
+    exit 1
+  fi
+  auto_dir="$auto_top/$desired_branch"
+  if test -d build; then
+    cur_branch=`readlink build/.branch`
+  else
+    cur_branch='/'
+  fi
+  if test "$desired_branch" != "$cur_branch"; then
+    if test "$cur_branch" != /; then
+      rm -f "$auto_top/$cur_branch"
+      mv build "$auto_top/$cur_branch"
     fi
-    auto_dir="$auto_top/$desired_branch"
-    if test -d build; then
-	cur_branch=`readlink build/.branch`
-    else
-	cur_branch='/'
-    fi
-    if test "$desired_branch" != "$cur_branch"; then
-	if test "$cur_branch" != /; then
-	    rm -f "$auto_top/$cur_branch"
-	    mv build "$auto_top/$cur_branch"
-	fi
-	test -d "$auto_dir" || mkdir "$auto_dir"
-	test -h "$auto_dir/.branch" || ln -s "$desired_branch" "$auto_dir/.branch"
-	mv "$auto_dir" build
-	ln -s ../build "$auto_dir"
-    fi
-    if test ! -h Makefile; then
-	rm -f Makefile
-	ln -s packaging/auto-Makefile Makefile
-    fi
-    echo $desired_branch
+    test -d "$auto_dir" || mkdir "$auto_dir"
+    test -h "$auto_dir/.branch" || ln -s "$desired_branch" "$auto_dir/.branch"
+    mv "$auto_dir" build
+    ln -s ../build "$auto_dir"
+  fi
+  if test ! -h Makefile; then
+    rm -f Makefile
+    ln -s packaging/auto-Makefile Makefile
+  fi
+  echo $desired_branch
 fi
diff --git a/rsync-ssl b/rsync-ssl
--- a/rsync-ssl
+++ b/rsync-ssl
@@ -17,132 +17,132 @@
 # Note that an stunnel connection requires at least version 4.x of stunnel.
 
 function rsync_ssl_run {
-    case "$*" in
+  case "$*" in
     *rsync://*) ;;
     *::*) ;;
     *)
-	echo "You must use rsync-ssl with a daemon-style hostname." 1>&2
-	exit 1
-	;;
-    esac
+      echo "You must use rsync-ssl with a daemon-style hostname." 1>&2
+      exit 1
+      ;;
+  esac
 
-    exec rsync --rsh="$0 --HELPER" "${@}"
+  exec rsync --rsh="$0 --HELPER" "${@}"
 }
 
 function rsync_ssl_helper {
-    if [[ -z "$RSYNC_SSL_TYPE" ]]; then
-	found=`path_search openssl stunnel4 stunnel` || exit 1
-	if [[ "$found" == */openssl ]]; then
-	    RSYNC_SSL_TYPE=openssl
-	    RSYNC_SSL_OPENSSL="$found"
-	elif [[ "$found" == */gnutls-cli ]]; then
-	    RSYNC_SSL_TYPE=gnutls
-	    RSYNC_SSL_GNUTLS="$found"
-	else
-	    RSYNC_SSL_TYPE=stunnel
-	    RSYNC_SSL_STUNNEL="$found"
-	fi
-    fi
-
-    case "$RSYNC_SSL_TYPE" in
-	openssl)
-	    if [[ -z "$RSYNC_SSL_OPENSSL" ]]; then
-		RSYNC_SSL_OPENSSL=`path_search openssl` || exit 1
-	    fi
-	    optsep=' '
-	    ;;
-	gnutls)
-	    if [[ -z "$RSYNC_SSL_GNUTLS" ]]; then
-		RSYNC_SSL_GNUTLS=`path_search gnutls-cli` || exit 1
-	    fi
-	    optsep=' '
-	    ;;
-	stunnel)
-	    if [[ -z "$RSYNC_SSL_STUNNEL" ]]; then
-		RSYNC_SSL_STUNNEL=`path_search stunnel4 stunnel` || exit 1
-	    fi
-	    optsep=' = '
-	    ;;
-	*)
-	    echo "The RSYNC_SSL_TYPE specifies an unknown type: $RSYNC_SSL_TYPE" 1>&2
-	    exit 1
-	    ;;
-    esac
-
-    if [[ -z "$RSYNC_SSL_CERT" ]]; then
-	certopt=""
-	gnutls_cert_opt=""
+  if [[ -z "$RSYNC_SSL_TYPE" ]]; then
+    found=`path_search openssl stunnel4 stunnel` || exit 1
+    if [[ "$found" == */openssl ]]; then
+      RSYNC_SSL_TYPE=openssl
+      RSYNC_SSL_OPENSSL="$found"
+    elif [[ "$found" == */gnutls-cli ]]; then
+      RSYNC_SSL_TYPE=gnutls
+      RSYNC_SSL_GNUTLS="$found"
     else
-	certopt="-cert$optsep$RSYNC_SSL_CERT"
-	gnutls_cert_opt="--x509certfile=$RSYNC_SSL_CERT"
+      RSYNC_SSL_TYPE=stunnel
+      RSYNC_SSL_STUNNEL="$found"
     fi
+  fi
 
-    if [[ -z "$RSYNC_SSL_KEY" ]]; then
-	keyopt=""
-	gnutls_key_opt=""
-    else
-	keyopt="-key$optsep$RSYNC_SSL_KEY"
-	gnutls_key_opt="--x509keyfile=$RSYNC_SSL_KEY"
-    fi
+  case "$RSYNC_SSL_TYPE" in
+    openssl)
+      if [[ -z "$RSYNC_SSL_OPENSSL" ]]; then
+        RSYNC_SSL_OPENSSL=`path_search openssl` || exit 1
+      fi
+      optsep=' '
+      ;;
+    gnutls)
+      if [[ -z "$RSYNC_SSL_GNUTLS" ]]; then
+        RSYNC_SSL_GNUTLS=`path_search gnutls-cli` || exit 1
+      fi
+      optsep=' '
+      ;;
+    stunnel)
+      if [[ -z "$RSYNC_SSL_STUNNEL" ]]; then
+        RSYNC_SSL_STUNNEL=`path_search stunnel4 stunnel` || exit 1
+      fi
+      optsep=' = '
+      ;;
+    *)
+      echo "The RSYNC_SSL_TYPE specifies an unknown type: $RSYNC_SSL_TYPE" 1>&2
+      exit 1
+      ;;
+  esac
 
-    if [[ -z ${RSYNC_SSL_CA_CERT+x} ]]; then
-	# RSYNC_SSL_CA_CERT unset - default CA set AND verify:
-	# openssl:
-	caopt="-verify_return_error -verify 4"
-	# gnutls:
-	gnutls_opts=""
-	# stunnel:
-	# Since there is no way of using the default CA certificate collection,
-	# we cannot do any verification. Thus, stunnel should really only be
-	# used if nothing else is available.
-	cafile=""
-	verify=""
-    elif [[ "$RSYNC_SSL_CA_CERT" == "" ]]; then
-	# RSYNC_SSL_CA_CERT set but empty -do NO verifications:
-	# openssl:
-	caopt="-verify 1"
-	# gnutls:
-	gnutls_opts="--insecure"
-	# stunnel:
-	cafile=""
-	verify="verifyChain = no"
-    else
-	# RSYNC_SSL_CA_CERT set - use CA AND verify:
-	# openssl:
-	caopt="-CAfile $RSYNC_SSL_CA_CERT -verify_return_error -verify 4"
-	# gnutls:
-	gnutls_opts="--x509cafile=$RSYNC_SSL_CA_CERT"
-	# stunnel:
-	cafile="CAfile = $RSYNC_SSL_CA_CERT"
-	verify="verifyChain = yes"
-    fi
+  if [[ -z "$RSYNC_SSL_CERT" ]]; then
+    certopt=""
+    gnutls_cert_opt=""
+  else
+    certopt="-cert$optsep$RSYNC_SSL_CERT"
+    gnutls_cert_opt="--x509certfile=$RSYNC_SSL_CERT"
+  fi
 
-    port="${RSYNC_PORT:-0}"
-    if [[ "$port" == 0 ]]; then
-	port="${RSYNC_SSL_PORT:-874}"
-    fi
+  if [[ -z "$RSYNC_SSL_KEY" ]]; then
+    keyopt=""
+    gnutls_key_opt=""
+  else
+    keyopt="-key$optsep$RSYNC_SSL_KEY"
+    gnutls_key_opt="--x509keyfile=$RSYNC_SSL_KEY"
+  fi
 
-    # If the user specified USER@HOSTNAME::module, then rsync passes us
-    # the -l USER option too, so we must be prepared to ignore it.
-    if [[ "$1" == "-l" ]]; then
-	shift 2
-    fi
+  if [[ -z ${RSYNC_SSL_CA_CERT+x} ]]; then
+    # RSYNC_SSL_CA_CERT unset - default CA set AND verify:
+    # openssl:
+    caopt="-verify_return_error -verify 4"
+    # gnutls:
+    gnutls_opts=""
+    # stunnel:
+    # Since there is no way of using the default CA certificate collection,
+    # we cannot do any verification. Thus, stunnel should really only be
+    # used if nothing else is available.
+    cafile=""
+    verify=""
+  elif [[ "$RSYNC_SSL_CA_CERT" == "" ]]; then
+    # RSYNC_SSL_CA_CERT set but empty -do NO verifications:
+    # openssl:
+    caopt="-verify 1"
+    # gnutls:
+    gnutls_opts="--insecure"
+    # stunnel:
+    cafile=""
+    verify="verifyChain = no"
+  else
+    # RSYNC_SSL_CA_CERT set - use CA AND verify:
+    # openssl:
+    caopt="-CAfile $RSYNC_SSL_CA_CERT -verify_return_error -verify 4"
+    # gnutls:
+    gnutls_opts="--x509cafile=$RSYNC_SSL_CA_CERT"
+    # stunnel:
+    cafile="CAfile = $RSYNC_SSL_CA_CERT"
+    verify="verifyChain = yes"
+  fi
 
-    hostname="$1"
-    shift
+  port="${RSYNC_PORT:-0}"
+  if [[ "$port" == 0 ]]; then
+    port="${RSYNC_SSL_PORT:-874}"
+  fi
 
-    if [[ -z "$hostname" || "$1" != rsync || "$2" != --server || "$3" != --daemon ]]; then
-	echo "Usage: rsync-ssl --HELPER HOSTNAME rsync --server --daemon ." 1>&2
-	exit 1
-    fi
+  # If the user specified USER@HOSTNAME::module, then rsync passes us
+  # the -l USER option too, so we must be prepared to ignore it.
+  if [[ "$1" == "-l" ]]; then
+    shift 2
+  fi
 
-    if [[ $RSYNC_SSL_TYPE == openssl ]]; then
-	exec $RSYNC_SSL_OPENSSL s_client $caopt $certopt $keyopt -quiet -verify_quiet -servername $hostname -verify_hostname $hostname -connect $hostname:$port
-    elif [[ $RSYNC_SSL_TYPE == gnutls ]]; then
-	exec $RSYNC_SSL_GNUTLS --logfile=/dev/null $gnutls_cert_opt $gnutls_key_opt $gnutls_opts $hostname:$port
-    else
-	# devzero@web.de came up with this no-tmpfile calling syntax:
-	exec $RSYNC_SSL_STUNNEL -fd 10 11<&0 <<EOF 10<&0 0<&11 11<&-
+  hostname="$1"
+  shift
+
+  if [[ -z "$hostname" || "$1" != rsync || "$2" != --server || "$3" != --daemon ]]; then
+    echo "Usage: rsync-ssl --HELPER HOSTNAME rsync --server --daemon ." 1>&2
+    exit 1
+  fi
+
+  if [[ $RSYNC_SSL_TYPE == openssl ]]; then
+    exec $RSYNC_SSL_OPENSSL s_client $caopt $certopt $keyopt -quiet -verify_quiet -servername $hostname -verify_hostname $hostname -connect $hostname:$port
+  elif [[ $RSYNC_SSL_TYPE == gnutls ]]; then
+    exec $RSYNC_SSL_GNUTLS --logfile=/dev/null $gnutls_cert_opt $gnutls_key_opt $gnutls_opts $hostname:$port
+  else
+    # devzero@web.de came up with this no-tmpfile calling syntax:
+    exec $RSYNC_SSL_STUNNEL -fd 10 11<&0 <<EOF 10<&0 0<&11 11<&-
 foreground = yes
 debug = crit
 connect = $hostname:$port
@@ -152,47 +152,47 @@ $verify
 $certopt
 $cafile
 EOF
-    fi
+  fi
 }
 
 function path_search {
-    IFS_SAVE="$IFS"
-    IFS=:
-    for prog in "${@}"; do
-	for dir in $PATH; do
-	    [[ -z "$dir" ]] && dir=.
-	    if [[ -f "$dir/$prog" && -x "$dir/$prog" ]]; then
-		echo "$dir/$prog"
-		IFS="$IFS_SAVE"
-		return 0
-	    fi
-	done
+  IFS_SAVE="$IFS"
+  IFS=:
+  for prog in "${@}"; do
+    for dir in $PATH; do
+      [[ -z "$dir" ]] && dir=.
+      if [[ -f "$dir/$prog" && -x "$dir/$prog" ]]; then
+        echo "$dir/$prog"
+        IFS="$IFS_SAVE"
+        return 0
+      fi
     done
+  done
 
-    IFS="$IFS_SAVE"
-    echo "Failed to find on your path: $*" 1>&2
-    echo "See the rsync-ssl manpage for configuration assistance." 1>&2
-    return 1
+  IFS="$IFS_SAVE"
+  echo "Failed to find on your path: $*" 1>&2
+  echo "See the rsync-ssl manpage for configuration assistance." 1>&2
+  return 1
 }
 
 if [[ "$#" == 0 ]]; then
-    echo "Usage: rsync-ssl [--type=SSL_TYPE] RSYNC_ARG [...]" 1>&2
-    echo "The SSL_TYPE can be openssl or stunnel"
-    exit 1
+  echo "Usage: rsync-ssl [--type=SSL_TYPE] RSYNC_ARG [...]" 1>&2
+  echo "The SSL_TYPE can be openssl or stunnel"
+  exit 1
 fi
 
 if [[ "$1" = --help || "$1" = -h ]]; then
-    exec rsync --help
+  exec rsync --help
 fi
 
 if [[ "$1" == --HELPER ]]; then
-    shift
-    rsync_ssl_helper "${@}"
+  shift
+  rsync_ssl_helper "${@}"
 fi
 
 if [[ "$1" == --type=* ]]; then
-    export RSYNC_SSL_TYPE="${1/--type=/}"
-    shift
+  export RSYNC_SSL_TYPE="${1/--type=/}"
+  shift
 fi
 
 rsync_ssl_run "${@}"
