Show the last compile error if we failed to create rounding.h.

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -82,7 +82,7 @@ flist.o: rounding.h
 
 rounding.h: rounding.c rsync.h
 	@for r in 0 1 3; do \
-	    if $(CC) $(CFLAGS) $(LDFLAGS) -o rounding -DEXTRA_ROUNDING=$$r -I. $(srcdir)/rounding.c >/dev/null 2>&1; then \
+	    if $(CC) $(CFLAGS) $(LDFLAGS) -o rounding -DEXTRA_ROUNDING=$$r -I. $(srcdir)/rounding.c >rounding.out 2>&1; then \
 		echo "#define EXTRA_ROUNDING $$r" >rounding.h; \
 		if test -f "$$HOME/build_farm/build_test.fns"; then \
 		    echo "EXTRA_ROUNDING is $$r" >&2; \
@@ -92,9 +92,11 @@ rounding.h: rounding.c rsync.h
 	done
 	@rm -f rounding
 	@if test -f rounding.h; then : ; else \
-	    echo "Failed to create rounding.h!"; \
+	    cat rounding.out 1>&2; \
+	    echo "Failed to create rounding.h!" 1>&2; \
 	    exit 1; \
 	fi
+	@rm -f rounding.out
 
 tls$(EXEEXT): $(TLS_OBJ)
 	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(TLS_OBJ) $(LIBS)
