Mention the auto-build-save setup.

diff --git a/packaging/prep-auto-dir b/packaging/prep-auto-dir
--- a/packaging/prep-auto-dir
+++ b/packaging/prep-auto-dir
@@ -15,6 +15,10 @@
 auto_top='auto-build-save'
 if test -d $auto_top -a -d .git; then
     desired_branch=`git rev-parse --abbrev-ref HEAD | tr / %`
+    if test "$desired_branch" = HEAD; then
+	echo "ERROR: switch to the right build dir manually when in detached HEAD mode." 1>&2
+	exit 1
+    fi
     auto_dir="$auto_top/$desired_branch"
     if test -d build; then
 	cur_branch=`readlink build/.branch`
